language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
  - make install
script:
  - set +e
  - make lint
  - make test
deploy:
  provider: pypi
  user: hbp_platform
  password:
    secure: kDkfXc/aVd7dcAuDlU4VXxu3orogmHzq7r/Ww4iefIp6A9TJv/imiF9/yVqsOodLhmzJWmGdAk+rmNnQ5yxHGcGE2629H5RA4AfhQLg8I0Dldey/1Dbq0PE2BdLf+3Sf53cru3FwyrOs3sjxVeqrzMa34UE4qByswyS9ZIVf0eh0erbLBjFjU+QyL48KKGyMlSnaYjlYWw93+3BW9dz11XRCH/2CudYNSdGaMjjsK6wjU2OJ2asw8qo2uNhTMtBkY2tuLcN9ByRavgeL3I9vuFhSKtWkRXVNLhDRRPujWI8FShsIwqWnxTHkhwcJdlsNa3NV2WDRP7e86ttNgcSQwZTMWS1d0PIjA6ZPGd8Zgp4bySmjCGCSZCtR65reR35rkJdqTstdkl9FLvqMqYFqALMvnCTZnFzIuKvuGu1RKIfNb8naijFMNiMdl4rZ8YxpG/0xiAwoB3FKHEFdA/4K/uPieIWlZSji+gp1wXhVd3yThlN1xTu5351VPIDsdmnKl3VhtxAxGP/o9pm7CexBm3xR7zdfZy8WDYvMhtfpTm2xULiUvKC9FQTq+596YDxhJVRS0sz9s7kyzntuwpKI6Ib/C1mWya3yNBVdGHs+0TgKHZfSnfbJgzh6wDkmR6oVtsjpAq28Ea5eR1oS+Nq2UkrR3s03uHegEXXtCmwC2ic=
  server: https://test.pypi.org/legacy/
